#+title: Anxiety for .tex files

This tool is aimed to help make sure reviewer response letters are consistent
with the paper text. Sometimes, we just need to compare everything to
everything... and then =anxiety= helps a little.

As of now, it is just a proof of concept, and not considered ready for use by
general public besides testing.

* Prerequisites

The program is usable as a single file ([[./anxiety.py]]). Prerequisites are:
#+begin_src bash
$ pip install --user diff_match_patch rich
#+end_src

Tested on Linux (please [[mailto:a@bochkarev.io][report]] if it works on Mac as well, if you have any info!)

* Usage:
The core function:
- in the =.tex= file(s), mark the blocks that you want to
  remain consistent using the comment lines as follows:

  #+begin_src latex
 % begin quote q1
  (your text here)

 % end quote q1
  #+end_src

  Then, if two such blocks appear across the input files, they will be =diff=-ed,
  and the changes will be highlighted in the program output. If an exclamation
  mark =!= appears anywhere in the quote ID (the text after `begin quote`, i.e.,
  `q1` in the example above), it is treated as 'canonical'. I.e., other
  encounters will be compared against this one.

  *Note:* In obvious cases (when the quotes are not embedded within each other),
  quote ID can be omitted in the `end quote` comment.

- To check consistency just feed the filenames to the tool as inputs, e.g.:

  #+begin_src bash
$ python -m anxiety tests/*.tex
  #+end_src


Example: see [[./tests/file1.tex]] (an "original text" file) and [[./tests/letter.tex]]
(a "letter with quotes"). To test the program:

  #+begin_src bash
$ python -m anxiety tests/file1.tex tests/letter.tex
  #+end_src

Further convenience magic: =python -m anxiety --show <WHAT> ./*.tex= will highlight regex matches. Specifically, depending on the value of =<WHAT>=:
- =talk= -- will show comments (i.e., custom tags used for comments/discussions, such as =\abinline=),
- =TODO= -- obviously, TODO keywords (as of now: =TODO= and =FIXME=).
- =comment-outs= -- highlight lines that comrise only comments (i.e., look as if
  they are completely commented out and perhaps should be deleted.)
- =quotes= (default) -- nothing, just make the quotes comparison as discussed above.
- =all= -- run all the possible checks.

* Notes

- The mapping between the quotes need not be one-to-one, in the sense that one
  canonical quote can be compared to arbitrary number of other notes, if the quote IDs coincide.
